# Generated by Django 3.1.4 on 2021-03-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=264)),
                ('apellido', models.CharField(max_length=264)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
                ('clave', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
