# Generated by Django 3.1.7 on 2021-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('A', 'ambos')], max_length=1)),
                ('clasificacion', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('numeroLikes', models.IntegerField()),
            ],
        ),
    ]
