# Generated by Django 3.1.4 on 2021-04-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rutina_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='clasificacion',
            field=models.CharField(choices=[('PIERNA', 'PIERNA'), ('BRAZO', 'BRAZO'), ('HOMBRO', 'HOMBRO'), ('ESPALDA', 'ESPALDA'), ('ABDOMEN', 'ABDOMEN'), ('CARDIO', 'CARDIO')], default='PIERNA', max_length=20),
        ),
    ]
