# Generated by Django 3.1.4 on 2021-04-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_comentario_ejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioXRutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.ejercicio')),
                ('rutina', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.rutina')),
            ],
        ),
    ]
