# Generated by Django 3.1.4 on 2021-04-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210413_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='repeticiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
