# Generated by Django 3.1.4 on 2021-04-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210413_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='series',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
