# Generated by Django 3.1.4 on 2021-04-29 00:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_usuarioxrutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario1', models.CharField(max_length=20)),
                ('usuario2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('mensaje', models.CharField(max_length=1000)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sala')),
            ],
        ),
    ]
