# Generated by Django 3.1.4 on 2021-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_historial_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='estatus',
            field=models.CharField(choices=[('SIN COMPARTIR', 'SIN COMPARTIR'), ('ESPERA', 'ESPERA'), ('APROBADO', 'APROBADO'), ('NO APROBADO', 'NO APROBADO')], default='SIN COMPARTIR', max_length=20),
        ),
    ]
