# Generated by Django 3.1.7 on 2021-05-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_experto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experto',
            name='clave',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=256),
        ),
    ]
